---
title: "RSV Study Enrollment"
output:
 word_document:
  reference_docx: word-styles-reference.docx
---

```{r enrollment, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
####################################################################################################
# Rowena Crow
# This code is to connect to redcap screening project and create a weekly report 
# for a hospital in a multi-site study
# The report is generated as a word document using R Markdown

# This report shows enrollment numbers (screened, eligible etc for last week 
# and the running total since study start)
#######################################################################################################

# need these - run once

#update.packages(ask=FALSE, repos="http://cran.rstudio.com")
#install.packages("devtools", repos="http://cran.rstudio.com")
#devtools::install_github(repo="OuhscBbmc/REDCapR")
#library(RCurl)
#library(REDCapR)
#library(httr)
library(knitr)
library(redcapAPI) #Load the package into the current R session.

#hospital ids as set in REDCap
site_1_id=3


# can set report to use today's here if needed
#report_date=Sys.Date( ) 

# or set to a particular date here
report_date=as.Date( "2018-08-17") 

# start of study
start_date=as.Date( "2018-04-30")
rpt_date_less_7<-report_date-7

#connect to REDCap project using API token
# DO NOT SHARE TOKEN !!!!!!!!!!!!
# export records from the Screening project
rcon <- redcapConnection(
  url   = "https://****/api/",
  token = "**************************"
)
# read all records
s_data<-exportRecords(rcon)


# use as.Date( ) to convert strings to dates 
s_data$days_since_screened<-report_date-(as.Date(s_data$screening_date))

# date ranges for the table
dt_range_1 <-paste(toString(format(start_date,format="%b %d")),"-",toString(format(rpt_date_less_7,format="%b %d %Y")))

# date range for the last week
dt_range_2 <-paste(toString(format(rpt_date_less_7+1,format="%b %d")),"-",toString(format(report_date,format="%b %d %Y")))

#Creating a blank dataframe for table A
table.a = as.data.frame(matrix(NA, 5,4))
# set row and column names  
colnames(table.a) = c( dt_range_1, dt_range_2, "Total", "% of total admissions")
rownames(table.a) = c( "Number of admissions", "- Screened", "- Eligible", "- Enrolled", "Participation rate(%)")
table.b<-table.a


# set counts
i_admissions = 0
i_screened = 0
i_eligible = 0
i_enrolled = 0

# screening_data

# Pasien setuju untuk terlibat dalam penelitian - Patients agree to be involved in the study


# get admission numbers 
hosp_1<-subset(s_data,hosp_id_bdg == site_1_id & s_data$admitted_yn =="Ya")
i_admissions=nrow(hosp_1)
#print(i_admissions)

# get admission numbers for last 7 days
hosp_1_last_week<- subset(hosp_1,days_since_screened< 8)
i_admissions_last_week=nrow(hosp_1_last_week)
#print(i_admissions_last_week)
i_admissions_rest<-i_admissions-i_admissions_last_week

i_admissions->table.a[1,3]
i_admissions_last_week->table.a[1,2]
i_admissions_rest->table.a[1,1]
" "->table.a[1,4]

# get screened numbers
hosp_1_screened<- subset(hosp_1,) # not sure the definintion/criteria???
i_screened=nrow(hosp_1_screened)
#print(i_screened)

# get screened numbers for last 7 days
hosp_1_screened_last_week<- subset(hosp_1_screened,days_since_screened< 8)
i_screened_last_week=nrow(hosp_1_screened_last_week)
#print(i_screened_last_week)
i_screened_rest<-i_screened-i_screened_last_week
x<-(i_screened/i_admissions)*100
screened_pc<-format(x, digits=3, nsmall=0)


i_screened->table.a[2,3]
i_screened_last_week->table.a[2,2]
i_screened_rest->table.a[2,1]
screened_pc->table.a[2,4]

# get screened numbers
hosp_1_eligible<- subset(hosp_1_screened, alri_dx_yn =="Ya")
i_eligible=nrow(hosp_1_eligible)

# get eligible numbers for last 7 days
hosp_1_eligible_last_week<- subset(hosp_1_eligible,days_since_screened< 8)
i_eligible=nrow(hosp_1_eligible)
i_eligible_last_week=nrow(hosp_1_eligible_last_week)
i_eligible_rest<-i_eligible-i_eligible_last_week
x<-(i_eligible/i_admissions)*100
eligible_pc<-format(x, digits=3, nsmall=0)



i_eligible->table.a[3,3]
i_eligible_last_week->table.a[3,2]
i_eligible_rest->table.a[3,1]
eligible_pc->table.a[3,4]


hosp_1_enrolled<-  subset(hosp_1_eligible, pt_consent_status == "Pasien setuju untuk terlibat dalam penelitian")
i_enrolled=nrow(hosp_1_enrolled)
# get enrolled numbers for last 7 days
hosp_1_enrolled_last_week<- subset(hosp_1_enrolled,days_since_screened< 8)
i_enrolled_last_week=nrow(hosp_1_enrolled_last_week)
i_enrolled_rest<-i_enrolled-i_enrolled_last_week
x<-(i_enrolled/i_admissions)*100
enrolled_pc<-format(x, digits=3, nsmall=0)

i_enrolled->table.a[4,3]
i_enrolled_last_week->table.a[4,2]
i_enrolled_rest->table.a[4,1]
enrolled_pc->table.a[4,4]

#calc participation rate ie. number enrolled/number eligible
x<-(i_enrolled/i_eligible)*100
partic_rate<-format(x, digits=3, nsmall=0)
x<-(i_enrolled_last_week/i_eligible_last_week)*100
partic_rate_last_week<-format(x, digits=3, nsmall=0)
x<-(i_enrolled_rest/i_eligible_rest)*100
partic_rate_rest<-format(x, digits=3, nsmall=0)


partic_rate->table.a[5,3]
partic_rate_last_week->table.a[5,2]
partic_rate_rest->table.a[5,1]
""->table.a[5,4]


# Print out Table A

```

**Table A.1.  Number of admissions and enrollments for Hospital 1**

```{r enrol_table}

kable(head(table.a), format = "markdown", row.names=TRUE, digits=1, caption=" ")







